M48
; DRILL file {KiCad (6.0.1)} date Sat Jan 29 17:05:39 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-29T17:05:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X4.7045Y-2.7144
X4.8955Y-2.7144
T2
X4.6927Y-2.5951
X4.9073Y-2.5951
T3
X3.34Y-2.6
X3.34Y-4.86
X6.86Y-2.6
X6.86Y-4.86
T0
M30
